# Generated by Django 4.0.4 on 2022-06-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(default='null', upload_to='movie'),
        ),
    ]
